export const recentActivityData = [
    {
      name: "Learner #1",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 5",
      reflectionQuality: 5,
      date: "Today 4:15",
    },
    {
      name: "Learner #2",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #3",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #4",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
    {
      name: "Learner #5",
      org: "Sales",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 5,
      date: "Yesterday 12:15",
    },
    {
      name: "Learner #6",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 5",
      reflectionQuality: 5,
      date: "Today 4:15",
    },
    {
      name: "Learner #7",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #8",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #9",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
    {
      name: "Learner #10",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 5",
      reflectionQuality: 5,
      date: "Today 4:15",
    },
    {
      name: "Learner #11",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #12",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #13",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
    {
      name: "Learner #14",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 5",
      reflectionQuality: 5,
      date: "Today 4:15",
    },
    {
      name: "Learner #15",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #16",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #17",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
    {
      name: "Learner #18",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #19",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #20",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
    {
      name: "Learner #21",
      org: "Marketing",
      status: "Behind",
      challenge: "Challenge 1",
      reflectionQuality: 2,
      date: "Yesterday 9:00",
    },
    {
      name: "Learner #22",
      org: "Tech",
      status: "On track",
      challenge: "Challenge 3",
      reflectionQuality: 4,
      date: "Yesterday 3:15",
    },
    {
      name: "Learner #23",
      org: "Sales",
      status: "On track",
      challenge: "Challenge 2",
      reflectionQuality: 3,
      date: "Yesterday 2:56",
    },
]